services:
  # keycloak:
  #   image: quay.io/keycloak/keycloak:26.2.0
  #   environment:
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./config/:/opt/keycloak/data/import:ro
  #   entrypoint: "/opt/keycloak/bin/kc.sh start-dev --import-realm"

  db:
    image: postgres:15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "collabhub"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=collabhub
      - POSTGRES_PASSWORD=collabhub
      - POSTGRES_DB=collabhub
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    # expose:
    #   - 5432
    ports:
      - 5432:5432
    expose:
      - 5432

  backend:
    build: .
    ports:
      - 7000:7000
    depends_on:
      db:
        condition: service_healthy
